AllCops:
  TargetRubyVersion: 2.4

Gemspec/RequiredRubyVersion:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/benchmark-memory.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/MethodLength:
  Exclude:
    - spec/**/*.rb
