AllCops:
  Include:
    - "Gemfile"
    - "Guardfile"
    - "Rakefile"
    - "*.gemspec"
  Exclude:
    - "vendor/**/*"
    - "db/schema.rb"
  TargetRubyVersion: 2.1

Naming/FileName:
  Description: Use snake_case for source file names.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#snake-case-files
  Enabled: true
  Exclude:
    - lib/benchmark-memory.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/MethodLength:
  Exclude:
    - spec/**/*.rb
