inherit_mode:
  merge:
    - Include
    - Exclude

AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable

Naming/FileName:
  Exclude:
    - lib/benchmark-memory.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
