cache: bundler
language: ruby
rvm:
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - ruby-head
script: bundle exec rspec
sudo: false

before_install: gem install bundler -v 1.14.3
bundler_args: --without development

matrix:
  allow_failures:
    - rvm: ruby-head
  include:
    - rvm: 2.4.0
      after_script:
        - bundle exec codeclimate-test-reporter

addons:
  code_climate:
    repo_token: 36f3969bdc1e5e821f38411648b9ba4217fa4518c9f58c30f0e9b0d1639b4f19
